import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getUser } from "./actions/auth/actions";
import { Navbar } from "./ui/Navbar";

const nunito = localFont({
  src: "./fonts/Nunito-VF.ttf",
  variable: "--font-nunito",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en">
      <body className={`min-h-screen ${nunito.variable}`}>
        <Navbar isUserLogged={Boolean(user)} />
        {children}
      </body>
    </html>
  );
}
